/**
 * generated by Xtext 2.25.0
 */
package dk.sdu.bdd.xtext.web;

/**
 * Initialization support for running Xtext languages in web applications.
 */
@SuppressWarnings("all")
public class BddDslWebSetup /* implements BddDslStandaloneSetup  */{
  @Override
  public /* Injector */Object createInjector() {
    throw new Error("Unresolved compilation problems:"
      + "\nThe method or field Guice is undefined"
      + "\nThe method or field Modules2 is undefined"
      + "\nBddDslRuntimeModule cannot be resolved."
      + "\nBddDslIdeModule cannot be resolved."
      + "\ncreateInjector cannot be resolved"
      + "\nmixin cannot be resolved");
  }
}
