/**
 * generated by Xtext 2.25.0
 */
package dk.sdu.bdd.xtext.web;

/**
 * Deploy this class into a servlet container to enable DSL-specific services.
 */
/* @WebServlet(, ) */@SuppressWarnings("all")
public class BddDslServlet /* implements XtextServlet  */{
  private static final long serialVersionUID = 1L;

  private /* DisposableRegistry */Object disposableRegistry;

  @Override
  public DisposableRegistry init() {
    throw new Error("Unresolved compilation problems:"
      + "\nThe method or field super is undefined"
      + "\nThe method createInjectorAndDoEMFRegistration() is undefined for the type BddDslWebSetup"
      + "\nThe method or field DisposableRegistry is undefined"
      + "\nThe field BddDslServlet.disposableRegistry refers to the missing type DisposableRegistry"
      + "\ninit cannot be resolved"
      + "\ngetInstance cannot be resolved");
  }

  @Override
  public Object destroy() {
    throw new Error("Unresolved compilation problems:"
      + "\nThe method or field super is undefined"
      + "\nThe field BddDslServlet.disposableRegistry refers to the missing type DisposableRegistry"
      + "\nThe field BddDslServlet.disposableRegistry refers to the missing type DisposableRegistry"
      + "\nThe field BddDslServlet.disposableRegistry refers to the missing type DisposableRegistry"
      + "\n!== cannot be resolved"
      + "\ndispose cannot be resolved"
      + "\ndestroy cannot be resolved");
  }
}
